http:
  routers:
    mealie:
      rule: "Host(`${MEALIE_DOMAIN}`)"
      entryPoints:
        - websecure
      service: mealie
      tls:
        certResolver: myresolver

  services:
    mealie:
      loadBalancer:
        servers:
          - url: "http://mealie-uiughk91s339sxvy1uq0ngym-195957807908:9000"
